apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgres://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  database-password: "{{ .Values.database.password }}"

