# Configuración de imagen PostgreSQL
image:
  repository: bitnami/postgresql
  tag: "15.5.0"
  pullPolicy: IfNotPresent

# Credenciales de base de datos
auth:
  username: pedidos
  password: pedidospass
  database: pedidos
  existingSecret: ""

# Configuración de réplicas
replicaCount: 1

# Configuración de persistencia
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce

# Configuración de recursos
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Configuración de PostgreSQL
postgresql:
  enabled: true
  auth:
    username: pedidos
    password: pedidospass
    database: pedidos
    existingSecret: ""
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
